In [1]:
import numpy as np
import pandas as  pd
from sklearn import svm

In [2]:
df=pd.read_csv(r'E:\KAGGLE PROJECTS\digit recognizer kaggle\train.csv')
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [3]:
x=df.iloc[0:25000,1:]
y=df.label.iloc[0:25000]

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [5]:
model=svm.SVC(kernel='linear', C=100, gamma=0.001)
model.fit(x_train,y_train)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [6]:
model.score(x_test,y_test)

0.91159999999999997

In [7]:
import cv2

In [19]:
# 2
c=cv2.imread(r'C:\Users\harshit\Downloads\image_12.jpg',0).ravel()
model.predict([c])

array([2], dtype=int64)

In [10]:
# 2
d=cv2.imread(r'C:\Users\harshit\Downloads\ezgif.com-gif-maker (1).jpg',0).ravel()  
model.predict([d])

array([2], dtype=int64)

In [11]:
# 2
e=cv2.imread(r'C:\Users\harshit\Downloads\mnbvc.jpg',0).ravel()
model.predict([e])

array([2], dtype=int64)

In [12]:
# 2
f=cv2.imread(r'C:\Users\harshit\Downloads\2_paint.jpg',0).ravel()
model.predict([f])

array([2], dtype=int64)

In [13]:
# 1
q=cv2.imread(r'C:\Users\harshit\Downloads\1_paint.jpg',0).ravel()   # wrong
model.predict([q])

array([5], dtype=int64)

In [14]:
# 5
w=cv2.imread(r'C:\Users\harshit\Downloads\5.jpg',0).ravel()
model.predict([w])

array([5], dtype=int64)

In [15]:
# 3
a=cv2.imread(r'C:\Users\harshit\Downloads\3_paint.jpg',0).ravel()   #wrong
model.predict([a])

array([0], dtype=int64)

In [16]:
# 8
z=cv2.imread(r'C:\Users\harshit\Downloads\eight.jpg',0).ravel()
model.predict([z])

array([8], dtype=int64)

In [17]:
# 8
b=cv2.imread(r'C:\Users\harshit\Downloads\image45.jpg',0).ravel()
model.predict([b])

array([8], dtype=int64)

In [20]:
# 9
m=cv2.imread(r'C:\Users\harshit\Downloads\9_paint.jpg',0).ravel()   # wrong
model.predict([m])

array([3], dtype=int64)

In [21]:
# 7
l=cv2.imread(r'C:\Users\harshit\Downloads\7...jpg',0).ravel()
model.predict([l])

array([7], dtype=int64)

In [27]:
# 6 
o=cv2.imread(r'C:\Users\harshit\Downloads\6.jpg',0).ravel()     # wrong
model.predict([o])

array([4], dtype=int64)

In [26]:
# 4
y=cv2.imread(r'C:\Users\harshit\Downloads\4.jpg',0).ravel()    # wrong
model.predict([y])

array([7], dtype=int64)