In [1]:
import numpy as np
import pandas as pd

df=pd.read_csv(r"E:\KAGGLE PROJECTS\digit recognizer kaggle\train.csv")
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [2]:
df.shape

(42000, 785)

In [3]:
Y=df.iloc[:1000,0]
x=df.iloc[:1000,1:]

In [4]:
y=Y.ravel()

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [10]:
from sklearn.model_selection import GridSearchCV
knn_1=KNeighborsClassifier()
grid_param={'n_neighbors':np.arange(1,25)}
knn_gscv=GridSearchCV(knn_1,grid_param,cv=5)
knn_gscv.fit(x,y)
knn_gscv.best_params_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'n_neighbors': 1}

In [7]:
knn.predict(x_test)

array([4, 2, 2, 9, 2, 0, 1, 9, 5, 2, 3, 1, 2, 1, 7, 9, 5, 7, 2, 4, 6, 1, 7,
       9, 4, 1, 1, 9, 5, 0, 2, 7, 7, 3, 9, 4, 1, 8, 3, 5, 7, 2, 4, 9, 2, 6,
       3, 3, 1, 7, 5, 0, 2, 6, 8, 9, 5, 3, 0, 0, 3, 8, 6, 3, 4, 1, 4, 5, 0,
       2, 0, 8, 5, 4, 6, 7, 2, 9, 1, 1, 0, 7, 5, 4, 2, 4, 0, 4, 1, 9, 0, 9,
       4, 5, 8, 2, 9, 2, 4, 7, 3, 2, 9, 8, 6, 1, 6, 7, 8, 0, 7, 0, 9, 1, 1,
       9, 5, 3, 5, 2, 8, 7, 4, 4, 0, 7, 6, 6, 3, 0, 6, 8, 1, 6, 3, 7, 3, 5,
       6, 1, 6, 4, 0, 1, 0, 6, 5, 7, 2, 8, 7, 0, 7, 5, 3, 3, 1, 0, 1, 6, 6,
       7, 2, 1, 5, 2, 2, 8, 0, 1, 6, 8, 5, 2, 7, 6, 1, 0, 8, 9, 1, 4, 2, 0,
       1, 0, 9, 1, 5, 0, 2, 1, 3, 4, 3, 2, 0, 2, 0, 4], dtype=int64)

In [9]:
knn.score(x_test,y_test)

0.875

In [12]:
knn_new=KNeighborsClassifier(n_neighbors=1)
knn_new.fit(x_train,y_train)
knn_new.predict(x_test)

array([4, 2, 2, 9, 2, 5, 1, 9, 5, 2, 5, 1, 2, 1, 7, 9, 5, 7, 2, 9, 6, 1, 7,
       9, 4, 1, 1, 7, 5, 0, 2, 7, 4, 8, 9, 4, 1, 8, 3, 5, 7, 2, 4, 9, 2, 9,
       3, 5, 1, 7, 5, 0, 2, 0, 8, 9, 5, 3, 0, 0, 3, 8, 6, 3, 4, 1, 4, 3, 0,
       2, 0, 8, 2, 9, 6, 7, 2, 9, 7, 1, 2, 7, 5, 4, 2, 4, 0, 4, 1, 9, 0, 9,
       4, 5, 8, 2, 9, 2, 4, 7, 3, 2, 9, 8, 6, 1, 6, 9, 8, 0, 7, 0, 9, 1, 1,
       4, 5, 3, 5, 2, 8, 7, 4, 4, 0, 7, 6, 6, 3, 0, 6, 8, 1, 6, 0, 7, 3, 5,
       6, 1, 6, 4, 0, 1, 0, 6, 5, 7, 2, 8, 7, 0, 7, 5, 3, 3, 3, 0, 1, 6, 6,
       7, 2, 1, 5, 2, 2, 8, 0, 8, 6, 8, 5, 2, 7, 6, 1, 0, 8, 9, 1, 4, 2, 0,
       1, 0, 9, 1, 5, 0, 0, 1, 3, 4, 3, 2, 0, 2, 0, 4], dtype=int64)

In [13]:
knn_new.score(x_test,y_test)

0.89500000000000002

In [14]:
import cv2

In [25]:
a=cv2.imread(r"C:\Users\harshit\Downloads\digits\ezgif.com-gif-maker (1).jpg",0).ravel   # correct
 
knn_new.predict([a])

array([2], dtype=int64)

In [26]:
b=cv2.imread(r"C:\Users\harshit\Downloads\digits\mnbvc.jpg",0).ravel()     # correct
knn_new.predict([b])

array([2], dtype=int64)

In [27]:
c=cv2.imread(r"C:\Users\harshit\Downloads\digits\mnbvc.jpg",0).ravel()   # correct
knn_new.predict([c])

array([2], dtype=int64)

In [29]:
d=cv2.imread(r"C:\Users\harshit\Downloads\digits\2_paint.jpg",0).ravel()   # correct
knn_new.predict([d])

array([2], dtype=int64)

In [33]:
e=cv2.imread(r"C:\Users\harshit\Downloads\digits\6.jpg",0).ravel()   # correct
knn_new.predict([e])

array([6], dtype=int64)